In [83]:
import pandas as pd

In [84]:
import numpy as np

In [85]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [86]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [87]:
pd.__version__

'2.3.3'

In [88]:
df.shape[0]

9704

In [89]:
df.fuel_type.nunique()

2

In [90]:
df.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

In [91]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [92]:
(df.isnull().sum() > 0).sum()

np.int64(4)

In [93]:
df.groupby('origin')['fuel_efficiency_mpg'].agg(['min', 'mean', 'max'])

             min       mean        max
origin
Asia    6.886245  14.973830  23.759123
Europe  6.200971  14.942532  25.967222
USA     6.695483  15.040204  24.971452

In [94]:
df[df.origin == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [95]:
median_screen = df['horsepower'].median()
median_screen

np.float64(149.0)

In [96]:
mode_screen = df['horsepower'].mode()[0]
mode_screen

np.float64(152.0)

In [97]:
df['horsepower'] = df['horsepower'].fillna(mode_screen)

In [98]:
new_median = df['horsepower'].median()
new_median

np.float64(152.0)

In [99]:
df_test = df[df.origin == 'Europe'][['vehicle_weight', 'model_year']][:7]
df_test

    vehicle_weight  model_year
0      3413.433759        2003
2      3079.038997        2018
4      3460.870990        2009
5      2484.883986        2008
10     3111.810181        2014
13     2274.735191        2000
16     2673.552941        2013

In [100]:
X = df_test.values
X

array([[3413.43375861, 2003.        ],
       [3079.03899737, 2018.        ],
       [3460.87098999, 2009.        ],
       [2484.88398604, 2008.        ],
       [3111.81018139, 2014.        ],
       [2274.73519056, 2000.        ],
       [2673.55294096, 2013.        ]])

In [101]:
XTX = X.T.dot(X)
XTX

array([[61289955.72540274, 41191663.53461886],
       [41191663.53461886, 28260843.        ]])

In [102]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 7.99397664e-07, -1.16516410e-06],
       [-1.16516410e-06,  1.73367254e-06]])

In [104]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [107]:
w = (XTX_inv @ X.T) @ y
w

array([-0.07188499,  0.63097065])

In [108]:
print(w.sum())

0.559085655434893